version: '3.6'
services:
  app:
    image: demo-puma
    volumes:
      - log:/app/log
      - tmp:/app/tmp
      - public:/app/public
  nginx:
    image: demo-nginx
    ports:
      - 80:80
    volumes:
      - log:/app/log
      - public:/app/public
  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  log:
  tmp:
  public:
  mysql:
