db:  
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: unodostres
    MYSQL_USER: root
    MYSQL_PASSWORD: unodostres
    MYSQL_DATABASE: falcon
  ports:
    - "3306:3306"
web:
  build: .
  command: foreman start
  ports:
    - "4000:3000"
  links:
    - db:db
    - memcached:memcached
  environment:
    MEMCACHED_SERVICE: memcached
memcached:
  image: memcached:latest
  ports:
    - "11211:11211"
