version: '3.6'
services:
  app:
    image: kalelc/demo-puma
    volumes:
      - app:/app
  nginx:
    image: kalelc/demo-nginx
    ports:
      - 80:80
    volumes:
      - app:/app
  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  app:
  mysql:
