development:
  adapter: mysql2
  database: beetrack_dev
  pool: 5
  host: localhost
  encoding: utf8
  username: root
  password: root

test:
  adapter: mysql2
  database: beetrack_test
  pool: 5
  host: localhost
  encoding: utf8
  username: root
  password: root

production:
  adapter: mysql2
  database: beetrack
  pool: 5
  host: localhost
  encoding: utf8
  username: root
  password: root
