default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_ENV_MYSQL_USER'] %>
  password: <%= ENV['DB_ENV_MYSQL_PASSWORD'] %>
  host: db
development:
  <<: *default
  database: falcon_development
test:
  <<: *default
  database: falcon_test
production:
  <<: *default
  database: falcon_production
  username: falcon
  password: <%= ENV['FALCON_DATABASE_PASSWORD'] %>
